# Generated by Django 3.2.12 on 2023-07-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_APP', '0002_alter_student_created_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100)),
                ('profile_image', models.FileField(upload_to='profile_image')),
            ],
        ),
    ]
