# Generated by Django 3.2.12 on 2023-07-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_APP', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='verify_otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
